/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
    | "Pacific/Midway"
    | "Pacific/Niue"
    | "Pacific/Honolulu"
    | "Pacific/Rarotonga"
    | "America/Anchorage"
    | "Pacific/Gambier"
    | "America/Los_Angeles"
    | "America/Tijuana"
    | "America/Denver"
    | "America/Phoenix"
    | "America/Chicago"
    | "America/Guatemala"
    | "America/New_York"
    | "America/Bogota"
    | "America/Caracas"
    | "America/Santiago"
    | "America/Buenos_Aires"
    | "America/Sao_Paulo"
    | "Atlantic/South_Georgia"
    | "Atlantic/Azores"
    | "Atlantic/Cape_Verde"
    | "Europe/London"
    | "Europe/Berlin"
    | "Africa/Lagos"
    | "Europe/Athens"
    | "Africa/Cairo"
    | "Europe/Moscow"
    | "Asia/Riyadh"
    | "Asia/Dubai"
    | "Asia/Baku"
    | "Asia/Karachi"
    | "Asia/Tashkent"
    | "Asia/Calcutta"
    | "Asia/Dhaka"
    | "Asia/Almaty"
    | "Asia/Jakarta"
    | "Asia/Bangkok"
    | "Asia/Shanghai"
    | "Asia/Singapore"
    | "Asia/Tokyo"
    | "Asia/Seoul"
    | "Australia/Brisbane"
    | "Australia/Sydney"
    | "Pacific/Guam"
    | "Pacific/Noumea"
    | "Pacific/Auckland"
    | "Pacific/Fiji";

export interface Config {
    auth: {
        users: UserAuthOperations;
    };
    blocks: {};
    collections: {
        users: User;
        media: Media;
        vehicles: Vehicle;
        colours: Colour;
        wheels: Wheel;
        packages: Package;
        occasions: Occasion;
        "payload-kv": PayloadKv;
        "payload-locked-documents": PayloadLockedDocument;
        "payload-preferences": PayloadPreference;
        "payload-migrations": PayloadMigration;
    };
    collectionsJoins: {};
    collectionsSelect: {
        users: UsersSelect<false> | UsersSelect<true>;
        media: MediaSelect<false> | MediaSelect<true>;
        vehicles: VehiclesSelect<false> | VehiclesSelect<true>;
        colors: ColorsSelect<false> | ColorsSelect<true>;
        wheels: WheelsSelect<false> | WheelsSelect<true>;
        packages: PackagesSelect<false> | PackagesSelect<true>;
        occasions: OccasionsSelect<false> | OccasionsSelect<true>;
        "payload-kv": PayloadKvSelect<false> | PayloadKvSelect<true>;
        "payload-locked-documents": PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
        "payload-preferences": PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
        "payload-migrations": PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
    };
    db: {
        defaultIDType: number;
    };
    fallbackLocale: null;
    globals: {};
    globalsSelect: {};
    locale: null;
    widgets: {
        collections: CollectionsWidget;
    };
    user: User;
    jobs: {
        tasks: unknown;
        workflows: unknown;
    };
}
export interface UserAuthOperations {
    forgotPassword: {
        email: string;
        password: string;
    };
    login: {
        email: string;
        password: string;
    };
    registerFirstUser: {
        email: string;
        password: string;
    };
    unlock: {
        email: string;
        password: string;
    };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
    id: number;
    updatedAt: string;
    createdAt: string;
    email: string;
    resetPasswordToken?: string | null;
    resetPasswordExpiration?: string | null;
    salt?: string | null;
    hash?: string | null;
    loginAttempts?: number | null;
    lockUntil?: string | null;
    sessions?:
        | {
              id: string;
              createdAt?: string | null;
              expiresAt: string;
          }[]
        | null;
    password?: string | null;
    collection: "users";
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
    id: number;
    alt: string;
    updatedAt: string;
    createdAt: string;
    url?: string | null;
    thumbnailURL?: string | null;
    filename?: string | null;
    mimeType?: string | null;
    filesize?: number | null;
    width?: number | null;
    height?: number | null;
    focalX?: number | null;
    focalY?: number | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "vehicles".
 */
export interface Vehicle {
    id: number;
    make: string;
    model: string;
    year: number;
    price: number;
    category: "sedan" | "suv" | "hatchback" | "coupe" | "stationwagen" | "mpv";
    fuelType: "petrol" | "diesel" | "electric" | "hybrid";
    image?: (number | null) | Media;
    features?:
        | {
              feature: string;
              id?: string | null;
          }[]
        | null;
    specs: {
        horsepower: number;
        /**
         * Nm
         */
        torque: number;
        /**
         * 0-100 km/h in seconds
         */
        acceleration: number;
        /**
         * km/h
         */
        topSpeed: number;
        /**
         * L/100km or kWh/100km for electric
         */
        fuelEfficiency: number;
        /**
         * km
         */
        range: number;
    };
    updatedAt: string;
    createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "colors".
 */
export interface Colour {
    id: number;
    name: string;
    /**
     * Hex color code e.g. #1a1a1a
     */
    hex: string;
    /**
     * Additional cost in EUR. Use 0 for included colors
     */
    priceModifier: number;
    updatedAt: string;
    createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "wheels".
 */
export interface Wheel {
    id: number;
    name: string;
    /**
     * Wheel diameter in inches
     */
    sizeInch: number;
    /**
     * Additional cost in EUR. Use 0 for included wheels.
     */
    priceModifier: number;
    updatedAt: string;
    createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "packages".
 */
export interface Package {
    id: number;
    name: string;
    description: string;
    features: {
        feature: string;
        id?: string | null;
    }[];
    /**
     * Additional cost in EUR
     */
    priceModifier: number;
    updatedAt: string;
    createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "occasions".
 */
export interface Occasion {
    id: number;
    /**
     * Brand: BMW, Volkswagen etc
     */
    make: string;
    /**
     * Model: M3, Golf GTI
     */
    model: string;
    /**
     * Year of registration
     */
    year: string;
    /**
     * Asking price in EURO
     */
    askingPrice: number;
    /**
     * Mileage in KM
     */
    mileage: number;
    Colour: string;
    transmission: "automatic" | "manual";
    condition: "new" | "used" | "demo";
    /**
     * Type one feature per line. Each line becomes a separate bullet point on the website.
     */
    featuresText?: string | null;
    features?:
        | {
              feature?: string | null;
              id?: string | null;
          }[]
        | null;
    /**
     * Upload your images here
     */
    images?:
        | {
              image: number | Media;
              /**
               * Optional "interior" or "Front view"
               */
              caption?: string | null;
              id?: string | null;
          }[]
        | null;
    /**
     * Additional notes about this car
     */
    description?: string | null;
    /**
     * Uncheck when this car has been sold
     */
    available?: boolean | null;
    updatedAt: string;
    createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
    id: number;
    key: string;
    data:
        | {
              [k: string]: unknown;
          }
        | unknown[]
        | string
        | number
        | boolean
        | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
    id: number;
    document?:
        | ({
              relationTo: "users";
              value: number | User;
          } | null)
        | ({
              relationTo: "media";
              value: number | Media;
          } | null)
        | ({
              relationTo: "vehicles";
              value: number | Vehicle;
          } | null)
        | ({
              relationTo: "colors";
              value: number | Colour;
          } | null)
        | ({
              relationTo: "wheels";
              value: number | Wheel;
          } | null)
        | ({
              relationTo: "packages";
              value: number | Package;
          } | null)
        | ({
              relationTo: "occasions";
              value: number | Occasion;
          } | null);
    globalSlug?: string | null;
    user: {
        relationTo: "users";
        value: number | User;
    };
    updatedAt: string;
    createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
    id: number;
    user: {
        relationTo: "users";
        value: number | User;
    };
    key?: string | null;
    value?:
        | {
              [k: string]: unknown;
          }
        | unknown[]
        | string
        | number
        | boolean
        | null;
    updatedAt: string;
    createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
    id: number;
    name?: string | null;
    batch?: number | null;
    updatedAt: string;
    createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
    updatedAt?: T;
    createdAt?: T;
    email?: T;
    resetPasswordToken?: T;
    resetPasswordExpiration?: T;
    salt?: T;
    hash?: T;
    loginAttempts?: T;
    lockUntil?: T;
    sessions?:
        | T
        | {
              id?: T;
              createdAt?: T;
              expiresAt?: T;
          };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
    alt?: T;
    updatedAt?: T;
    createdAt?: T;
    url?: T;
    thumbnailURL?: T;
    filename?: T;
    mimeType?: T;
    filesize?: T;
    width?: T;
    height?: T;
    focalX?: T;
    focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "vehicles_select".
 */
export interface VehiclesSelect<T extends boolean = true> {
    make?: T;
    model?: T;
    year?: T;
    price?: T;
    category?: T;
    fuelType?: T;
    image?: T;
    features?:
        | T
        | {
              feature?: T;
              id?: T;
          };
    specs?:
        | T
        | {
              horsepower?: T;
              torque?: T;
              acceleration?: T;
              topSpeed?: T;
              fuelEfficiency?: T;
              range?: T;
          };
    updatedAt?: T;
    createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "colors_select".
 */
export interface ColorsSelect<T extends boolean = true> {
    name?: T;
    hex?: T;
    priceModifier?: T;
    updatedAt?: T;
    createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "wheels_select".
 */
export interface WheelsSelect<T extends boolean = true> {
    name?: T;
    sizeInch?: T;
    priceModifier?: T;
    updatedAt?: T;
    createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "packages_select".
 */
export interface PackagesSelect<T extends boolean = true> {
    name?: T;
    description?: T;
    features?:
        | T
        | {
              feature?: T;
              id?: T;
          };
    priceModifier?: T;
    updatedAt?: T;
    createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "occasions_select".
 */
export interface OccasionsSelect<T extends boolean = true> {
    make?: T;
    model?: T;
    year?: T;
    askingPrice?: T;
    mileage?: T;
    Colour?: T;
    transmission?: T;
    condition?: T;
    featuresText?: T;
    features?:
        | T
        | {
              feature?: T;
              id?: T;
          };
    images?:
        | T
        | {
              image?: T;
              caption?: T;
              id?: T;
          };
    description?: T;
    available?: T;
    updatedAt?: T;
    createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
    key?: T;
    data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
    document?: T;
    globalSlug?: T;
    user?: T;
    updatedAt?: T;
    createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
    user?: T;
    key?: T;
    value?: T;
    updatedAt?: T;
    createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
    name?: T;
    batch?: T;
    updatedAt?: T;
    createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
    data?: {
        [k: string]: unknown;
    };
    width: "full";
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
    [k: string]: unknown;
}

declare module "payload" {
    export interface GeneratedTypes extends Config {}
}
